### ISSUE TITLE
Facebook login sometimes works but other times returns 308 error

### ISSUE THREAD

**Issue by freakstatic** [facebook/facebook-swift-sdk#302]
I try to login with Facebook but the request sometimes fails and sometimes just works fine. Let's say that in 5 attempts at least 1 fails

## Environment

- Swift Version: 4.2
- Cocoapods version 1.5.3

FBSDKCoreKit (4.39.0) 
FBSDKLoginKit (4.39.0)
FBSDKShareKit (4.39.0)
FacebookCore (0.5.0)
FacebookLogin (0.5.0) 
FacebookShare (0.5.0)

## Actual Results

2018-12-14 15:57:24.381591+0000 pprr-app[6928:56565] Falling back to storing access token in NSUserDefaults because of simulator bug
2018-12-14 15:57:24.398436+0000 pprr-app[6928:56565] Unknown class MyList in Interface Builder file.
2018-12-14 15:57:26.243171+0000 pprr-app[6928:56565] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2018-12-14 15:57:26.243388+0000 pprr-app[6928:56565] Falling back to storing access token in NSUserDefaults because of simulator bug
2018-12-14 15:57:26.244520+0000 pprr-app[6928:56565] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
TraceSQL(0x7f9ca6e031c0): SELECT r.version, r.storage_policy, b.response_object, b.proto_props, d.isDataOnFS, d.receiver_data, b.request_object, b.user_info, r.time_stamp FROM cfurl_cache_response r, cfurl_cache_blob_data b, cfurl_cache_receiver_data d WHERE r.request_key='https://graph.facebook.com/v3.2/323423565141717/activities' AND b.entry_ID=r.entry_ID AND b.entry_ID=d.entry_ID;
2018-12-14 15:57:26.552863+0000 pprr-app[6928:56612] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C24.1:2][0x7f9cab80b5f0] get output frames failed, state 8196
2018-12-14 15:57:26.553056+0000 pprr-app[6928:56612] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C24.1:2][0x7f9cab80b5f0] get output frames failed, state 8196
2018-12-14 15:57:26.553408+0000 pprr-app[6928:56612] TIC Read Status [24:0x0]: 1:57
2018-12-14 15:57:26.553550+0000 pprr-app[6928:56612] TIC Read Status [24:0x0]: 1:57
TraceSQL(0x7f9ca6e031c0): SELECT r.version, r.storage_policy, b.response_object, b.proto_props, d.isDataOnFS, d.receiver_data, b.request_object, b.user_info, r.time_stamp FROM cfurl_cache_response r, cfurl_cache_blob_data b, cfurl_cache_receiver_data d WHERE r.request_key='https://graph.facebook.com/v3.2/323423565141717/activities' AND b.entry_ID=r.entry_ID AND b.entry_ID=d.entry_ID;
2018-12-14 15:57:27.884798+0000 pprr-app[6928:56662] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C25.1:2][0x7f9ca9407cf0] get output frames failed, state 8196
2018-12-14 15:57:27.884936+0000 pprr-app[6928:56662] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C25.1:2][0x7f9ca9407cf0] get output frames failed, state 8196
2018-12-14 15:57:27.885291+0000 pprr-app[6928:56662] TIC Read Status [25:0x0]: 1:57
2018-12-14 15:57:27.885449+0000 pprr-app[6928:56662] TIC Read Status [25:0x0]: 1:57
2018-12-14 15:57:30.527632+0000 pprr-app[6928:56565] Falling back to loading access token from NSUserDefaults because of simulator bug
2018-12-14 15:57:30.527841+0000 pprr-app[6928:56565] Falling back to storing access token in NSUserDefaults because of simulator bug
The operation couldn’t be completed. (com.facebook.sdk.login error 308.)
2018-12-14 15:57:32.711202+0000 pprr-app[6928:56565] The "OK" alert occured.

## Steps to Reproduce

Just try to login and logout multiple times

## Code Samples & Details

`loginManager.logIn(readPermissions: [.publicProfile], viewController: self) { loginResult in
            
            switch loginResult {
            case .failed(let error):
                let alert = Utils.triggerAlert(title: "Error", error: "Error received!")
                print(error.localizedDescription)
                self.present(alert, animated: true)
                
                return
            case .cancelled:
                print("Facebook login canceled")
                return;
            case .success(let grantedPermissions, let declinedPermissions, let accessToken):
                print("Facebook login success")
                
            }
        }`

**Comment by robtimp** [comment]
This issue should now be fixed on the master branch of facebook-objc-sdk, but there is not yet a release version of the fix (though we’re hoping to have one out ASAP).

In the meantime, please use this workaround:

Add
pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
to your podfile.

**Comment by prundianudaniel** [comment]
@robtimp: I tried to do that, but unfortunately this haven't changed anything.

**Comment by robtimp** [comment]
@prundianudaniel Try `pod deintegrate` then `pod install` to make sure it's using the latest version. 

If you still see the issue, please reach out to us here if you have not done so already: https://developers.facebook.com/support

**Comment by freakstatic** [comment]
> This issue should now be fixed on the master branch of facebook-objc-sdk, but there is not yet a release version of the fix (though we’re hoping to have one out ASAP).
> 
> In the meantime, please use this workaround:
> 
> Add
> `pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'`
> to your podfile.

Thanks! It's working fine now :)

**Comment by loevborg** [comment]
Works for me to point on `master` as well, looking forward to a release of this 👍

**Comment by gtroshin** [comment]
Looking forward to have it fixed in Swift SDK! Very annoying issue.

**Comment by georgmay** [comment]
@robtimp What version of `FBSDKLoginKit` we supposed to set?

**Comment by georgmay** [comment]
@robtimp I've done everything suggested above, still receiving 
"The operation couldn’t be completed. (com.facebook.sdk.login error 308.)". Funny thing is this behavior is non deterministic.

**Comment by Lyankar** [comment]
2018-12-14 15:57:24.381591+0000 pprr-app[6928:56565] Falling back to storing access token in NSUserDefaults because of simulator bug

For this error , the solution is run your app in real device not in Simulator.
