### ISSUE TITLE
iOS Deprecated API Usage Warning

### ISSUE THREAD

**Issue by carlosdamiao** [facebook/facebook-swift-sdk#527]
After submitting an App to Testflight I got an e-mail from Apple with the following:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After some search throughout my project, I've found that this library is using UIWebView APIs. Are you planning on removing them?

As far as I can tell, facebook-objc-sdk is already using WKWebView.
Thanks

**Comment by davidrothera** [comment]
Have you updated to the latest version? We pushed a new version last week which updated this.

**Comment by ajay-simform** [comment]
@davidrothera Yes, I have updated to the latest version and still getting this warning from Apple.

**Comment by ajay-simform** [comment]
Hey @davidrothera I can see a reference of this library https://github.com/AliSoftware/OHHTTPStubs in one of cartfile(https://github.com/facebook/facebook-objc-sdk/blob/8e4d90a43010ed567a59cf515be6b654b9e719c6/Cartfile.private) which uses AFNetworking internally. If this is true, I am afraid AFNetworking has this issue still open, https://github.com/AFNetworking/AFNetworking/issues/4428

**Comment by carlosdamiao** [comment]
I've noticed that, although I've run "pod update FacebookCore", it doesn't actually update the pod. I'm stuck at 0.5.0 and that might be the issue.

**Comment by carlosdamiao** [comment]
@davidrothera I can confirm that after running "pod update FacebookCore FacebookShare FacebookLogin" I've successfully update all 3 pods and that I don't have any UIWebView dependency.

Thanks and sorry for bothering!

**Comment by davidrothera** [comment]
No worries at all 😀
